apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: nimbus
  name: nimbus
spec:
  ports:
    - name: "6627"
      port: 6627
      targetPort: 6627
  selector:
    service: nimbus
status:
  loadBalancer: {}
